const keys = ['title', 'loading', 'refresh', 'unavailable', 'unmatched', 'temperature', 'wind', 'gusts', 'storm', 'west', 'central', 'east', 'level0', 'level1', 'level2', 'unknown', 'published', 'sampled', 'quality', 'pass', 'fail', 'stale', 'stationNote', 'sampleNote', 'stormNote', 'windForecast', 'waveForecast', 'open', 'showForecast', 'forecastNote', 'checked']
const messages = {
  hu: ['Balaton · hivatalos mérések', 'Hivatalos adatok betöltése…', 'Frissítés', 'A forrás most nem érhető el.', 'Ehhez a strandhoz nincs biztosan azonosított vízminta.', 'Vízhőmérséklet', 'Mért szél', 'Széllökés', 'Viharjelzés', 'Nyugati medence', 'Középső medence', 'Keleti medence', 'Alapállapot', 'I. fok', 'II. fok', 'Nem ismert', 'Forrás frissítése', 'Mintavétel', 'Legutóbbi vízminta', 'Megfelelő minta', 'Nem megfelelő minta', 'Régi adat — ellenőrizd a forrásnál', 'Mérőállomási adatok; a kiválasztott strandnál eltérhetnek. Az időpont a forrás közzétételi ideje.', 'A vízminta a mintavétel időpontját jellemzi; nem igazolja a jelenlegi állapotot.', 'A medencéd jelzését és a helyszíni fényjelzést ellenőrizd. Az alapállapot önmagában nem úszási ajánlás.', 'Szélelőrejelzés', 'Hullámmagasság-előrejelzés', 'Hivatalos forrás', 'Térkép betöltése', 'HungaroMet előrejelzés magyar nyelven. Az érvényességi idő a térképen látható. Ha nem töltődik be, nyisd meg a hivatalos forrást.', 'Lekérdezve'],
  en: ['Balaton · official observations', 'Loading official data…', 'Refresh', 'This source is currently unavailable.', 'No confidently matched water sample for this beach.', 'Water temperature', 'Observed wind', 'Gusts', 'Storm warnings', 'Western basin', 'Central basin', 'Eastern basin', 'Base state', 'Level I', 'Level II', 'Unknown', 'Source updated', 'Sample taken', 'Latest water sample', 'Sample passed', 'Sample failed', 'Old data — check the source', 'Station observations may differ at your beach. The timestamp is the source publication time.', 'The sample describes the sampling date; it does not confirm current conditions.', 'Check your basin and the lights on site. Base state alone is not a swimming recommendation.', 'Wind forecast', 'Wave-height forecast', 'Official source', 'Load map', 'HungaroMet forecast in Hungarian. Validity is shown on the map. If it does not load, open the official source.', 'Retrieved'],
  fr: ['Balaton · mesures officielles', 'Chargement des données…', 'Actualiser', 'Source indisponible.', 'Aucun prélèvement identifié avec certitude pour cette plage.', 'Température de l’eau', 'Vent mesuré', 'Rafales', 'Alertes de tempête', 'Bassin ouest', 'Bassin central', 'Bassin est', 'État de base', 'Niveau I', 'Niveau II', 'Inconnu', 'Source actualisée', 'Prélèvement', 'Dernier prélèvement', 'Échantillon conforme', 'Échantillon non conforme', 'Données anciennes — vérifiez la source', 'Mesures aux stations : les conditions de votre plage peuvent différer. Heure de publication de la source.', 'Le prélèvement décrit sa date, sans confirmer les conditions actuelles.', 'Vérifiez votre bassin et les signaux sur place. L’état de base ne recommande pas la baignade.', 'Prévisions du vent', 'Prévisions des vagues', 'Source officielle', 'Charger la carte', 'Prévisions HungaroMet en hongrois. Validité sur la carte. Si elle ne charge pas, ouvrez la source.', 'Consulté'],
  it: ['Balaton · misure ufficiali', 'Caricamento dati…', 'Aggiorna', 'Fonte non disponibile.', 'Nessun campione associato con certezza a questa spiaggia.', 'Temperatura dell’acqua', 'Vento misurato', 'Raffiche', 'Allerta temporali', 'Bacino occidentale', 'Bacino centrale', 'Bacino orientale', 'Stato base', 'Livello I', 'Livello II', 'Sconosciuto', 'Fonte aggiornata', 'Prelievo', 'Ultimo campione', 'Campione conforme', 'Campione non conforme', 'Dati vecchi — controlla la fonte', 'Le misure delle stazioni possono differire dalla spiaggia. L’orario indica la pubblicazione della fonte.', 'Il campione descrive la data del prelievo, non conferma le condizioni attuali.', 'Controlla il bacino e i segnali sul posto. Lo stato base non è una raccomandazione di nuoto.', 'Previsione del vento', 'Previsione delle onde', 'Fonte ufficiale', 'Carica mappa', 'Previsione HungaroMet in ungherese. Validità sulla mappa. Se non si carica, apri la fonte.', 'Consultato'],
  es: ['Balaton · mediciones oficiales', 'Cargando datos…', 'Actualizar', 'Fuente no disponible.', 'No hay una muestra identificada con certeza para esta playa.', 'Temperatura del agua', 'Viento medido', 'Ráfagas', 'Alertas de tormenta', 'Cuenca occidental', 'Cuenca central', 'Cuenca oriental', 'Estado base', 'Nivel I', 'Nivel II', 'Desconocido', 'Fuente actualizada', 'Muestreo', 'Última muestra', 'Muestra conforme', 'Muestra no conforme', 'Datos antiguos — consulta la fuente', 'Las mediciones de las estaciones pueden diferir de tu playa. La hora indica la publicación de la fuente.', 'La muestra describe la fecha del muestreo; no confirma las condiciones actuales.', 'Comprueba tu cuenca y las señales locales. El estado base no es una recomendación de baño.', 'Previsión del viento', 'Previsión de olas', 'Fuente oficial', 'Cargar mapa', 'Previsión HungaroMet en húngaro. Validez en el mapa. Si no carga, abre la fuente.', 'Consultado'],
}
export function balatonMessages(language) {
  return Object.fromEntries(keys.map((key, index) => [key, (messages[language] ?? messages.en)[index]]))
}
