const messages = {
  hu: { close:'Bezárás', chipUnavailable:'Riasztási adat nem ellenőrizhető', chipNone:'Nincs kiadott figyelmeztetés', title:'Időjárási figyelmeztetések', loading:'Riasztások ellenőrzése…', unavailable:'A friss riasztási helyzet nem ellenőrizhető.', stale:'Régi riasztási adat — ellenőrizd a hivatalos forrásnál.', none:'A forrás nem közöl érvényes figyelmeztetést erre a régióra. Ez önmagában nem úszási engedély.', active:'Érvényben', future:'Későbbi időszakra', checked:'Ellenőrizve', issued:'Kiadva', source:'Hivatalos figyelmeztetés', scope:'Területi időjárási figyelmeztetés; a tavi viharjelzést külön ellenőrizd.', details:'Részletek és teendők', danger:'Időjárási figyelmeztetés: ne menj vízbe.', caution:'Területi időjárási figyelmeztetés van érvényben.', action:'Ellenőrizd a hivatalos figyelmeztetést és a helyszíni jelzéseket.', levels:{2:'Sárga',3:'Narancs',4:'Piros'} },
  en: { close:'Close', chipUnavailable:'Warning status unverified', chipNone:'No warnings issued', title:'Weather warnings', loading:'Checking warnings…', unavailable:'The latest warning status could not be verified.', stale:'Outdated warning data — check the official source.', none:'The source reports no valid warning for this region. This alone does not mean it is safe to swim.', active:'In effect', future:'Upcoming', checked:'Checked', issued:'Issued', source:'Official warning', scope:'Regional weather warning; check lake storm signals separately.', details:'Details and instructions', danger:'Weather warning: stay out of the water.', caution:'A regional weather warning is in effect.', action:'Check the official warning and on-site signals.', levels:{2:'Yellow',3:'Orange',4:'Red'} },
  fr: { close:'Fermer', chipUnavailable:'Alertes non vérifiées', chipNone:'Aucune alerte émise', title:'Alertes météo', loading:'Vérification des alertes…', unavailable:'Les alertes récentes ne peuvent pas être vérifiées.', stale:'Données anciennes — consultez la source officielle.', none:'Aucune alerte valide signalée pour cette région. Cela ne garantit pas une baignade sûre.', active:'En cours', future:'À venir', checked:'Vérifié', issued:'Émis', source:'Alerte officielle', scope:'Alerte régionale ; vérifiez séparément les signaux du lac.', details:'Détails et consignes', danger:'Alerte météo : restez hors de l’eau.', caution:'Une alerte météo régionale est en vigueur.', action:'Consultez l’alerte officielle et les signaux sur place.', levels:{2:'Jaune',3:'Orange',4:'Rouge'} },
  it: { close:'Chiudi', chipUnavailable:'Allerte non verificate', chipNone:'Nessuna allerta emessa', title:'Allerte meteo', loading:'Verifica delle allerte…', unavailable:'Impossibile verificare le allerte aggiornate.', stale:'Dati non aggiornati — consulta la fonte ufficiale.', none:'Nessuna allerta valida segnalata per la regione. Questo non garantisce una balneazione sicura.', active:'In corso', future:'In arrivo', checked:'Verificato', issued:'Emesso', source:'Allerta ufficiale', scope:'Allerta regionale; verifica separatamente i segnali del lago.', details:'Dettagli e istruzioni', danger:'Allerta meteo: resta fuori dall’acqua.', caution:'È in vigore un’allerta meteo regionale.', action:'Controlla l’allerta ufficiale e i segnali sul posto.', levels:{2:'Gialla',3:'Arancione',4:'Rossa'} },
  es: { close:'Cerrar', chipUnavailable:'Avisos sin verificar', chipNone:'Sin avisos emitidos', title:'Avisos meteorológicos', loading:'Comprobando avisos…', unavailable:'No se pudieron verificar los avisos actuales.', stale:'Datos antiguos — consulta la fuente oficial.', none:'La fuente no comunica avisos vigentes para esta región. Esto no garantiza un baño seguro.', active:'Vigente', future:'Próximo', checked:'Comprobado', issued:'Emitido', source:'Aviso oficial', scope:'Aviso regional; consulta por separado las señales del lago.', details:'Detalles e instrucciones', danger:'Aviso meteorológico: no entres en el agua.', caution:'Hay un aviso meteorológico regional vigente.', action:'Consulta el aviso oficial y las señales locales.', levels:{2:'Amarillo',3:'Naranja',4:'Rojo'} },
}
export const weatherAlertMessages = language => messages[language?.split('-')[0]] ?? messages.en
export function activeWeatherWarning(state, time, now = Date.now()) {
  if (state?.status !== 'available' || state.error || state.loading || !Number.isFinite(Date.parse(state.checkedAt)) || now - Date.parse(state.checkedAt) > 10 * 60000) return null
  const timestamp = typeof time === 'number' ? time : Date.parse(time)
  return state.items?.filter(item => Date.parse(item.startsAt) <= timestamp && Date.parse(item.expiresAt) > timestamp).sort((a,b) => Number(b.hazard === 3)-Number(a.hazard === 3) || b.level-a.level)[0] ?? null
}
export function weatherWarningDuringInterval(state, startsAt, endsAt, now = Date.now()) {
  const start=Date.parse(startsAt), end=Date.parse(endsAt)
  return state?.items?.some(item => Date.parse(item.startsAt)<end && Date.parse(item.expiresAt)>start
    && activeWeatherWarning(state,Math.max(start,Date.parse(item.startsAt)),now)) ?? false
}

export function weatherWarningsAt(items, time) {
  const timestamp = typeof time === 'number' ? time : Date.parse(time)
  return (items ?? []).filter(item => Date.parse(item.startsAt) <= timestamp && Date.parse(item.expiresAt) > timestamp)
}
